name: Arduino Compile

on:
  push:
    paths:
      - "arduino-uno-r4/**"
  pull_request:
    paths:
      - "arduino-uno-r4/**"

jobs:
  compile-uno-r4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: arduino:renesas_uno:unor4wifi
          sketch-paths: arduino-uno-r4/main
          libraries: |
            - name: ArduinoBLE
            - name: ArduinoGraphics
            - name: DHT11
